#!/bin/sh
set -e

LAUNCH_AGENTS_DIR="$HOME/Library/LaunchAgents"
LAUNCH_AGENT_PLIST="$LAUNCH_AGENTS_DIR/com.ntrippar.sekey.plist"

# This directory should already exist, but some users have had issues with it
# being missing.
mkdir -p "$LAUNCH_AGENTS_DIR"

# write the LaunchAgent Plist
cat > "$LAUNCH_AGENT_PLIST" << EOT
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.ntrippar.sekey</string>
    <key>ProgramArguments</key>
    <array>
        <string>/Applications/SeKey.app/Contents/MacOS/sekey</string>
        <string>--daemon</string>
    </array>
    <key>StandardErrorPath</key>
    <string>/dev/null</string>
    <key>StandardOutPath</key>
    <string>/dev/null</string>
    <key>KeepAlive</key>
    <true/>
</dict>
</plist>
EOT

#fix permissions, also so it runs at the current user
chown "${USER}:staff" "$LAUNCH_AGENT_PLIST"

# Launch the app
sudo -u "${USER}" launchctl load "$LAUNCH_AGENT_PLIST"

exit 0
